tituly_bn <- c("Bc", "Ing.arch.", "Ing.Arch.", "Ing", "ThMgr", "Mgr", "PharmDr", "PaedDr", "PhDr", "PHDr", "MUDr", "JUDr", "Doc", "prof")
tituly_an <- c("MBA", "MSc", "Ph.D.", "PH.D.")

# Loop over each donation form
for (d in donationform) {
  
  # Load data
  data <- readRDS(paste0("intermediate_data/donation_data_", d, ".rds"))
  
  # Define the polparty variable as a factor with labels
  #data <- data %>%
  #  mutate(polparty = factor(polparty, levels = 1:12, labels = polparty))
  data$polparty=factor(data$polparty, levels = 1:12, labels = polparty)
  
  # Sort data
  data <- data %>%
    arrange(polparty, surname, firstname, birthdate, year)
  
  # Create and clean acadegree_an and acadegree_bn
  data <- data %>%
    mutate(acadegree_an = if_else(is.na(titulza) | titulza == "", ".", titulza),
           acadegree_bn = if_else(!is.na(titulpřed) & titulpřed != " ", titulpřed, ".")) %>%
    mutate(acadegree_an = as.character(acadegree_an),
           acadegree_bn = as.character(acadegree_bn))
  
  # Rename donation variable
  if (d=="financial"){
    
    
    data = data %>% 
      rename(
        "financial_donation" = "částkakc"
      )
    
    # Keep only the necessary variables
    data <- data %>%
      select(surname, firstname, acadegree_an, acadegree_bn, birthdate, year, polparty, financial_donation)
    
  } else{
    
    data = data %>% 
      rename(
        "nonfinancial_donation" = "hodnotabúpkč"
      )
    
    # Keep only the necessary variables
    data <- data %>%
      select(surname, firstname, acadegree_an, acadegree_bn, birthdate, year, polparty, nonfinancial_donation)
    
  }
  
  # Filter out specific surnames
  data <- data %>%
    filter(!surname %in% c("anonym", "test", "Test", "stojkov"))
  
  # Replace academic titles in firstname and surname using tituly_bn and tituly_an
  for (t in tituly_bn) {
    data <- data %>%
      mutate(acadegree_bn = if_else(str_detect(firstname, fixed(t)), t, acadegree_bn),
             acadegree_bn = if_else(str_detect(surname, fixed(t)), t, acadegree_bn))
  }
  
  for (t in tituly_an) {
    data <- data %>%
      mutate(acadegree_an = if_else(str_detect(firstname, fixed(t)), t, acadegree_an),
             acadegree_an = if_else(str_detect(surname, fixed(t)), t, acadegree_an))
  }
  
  # Clean up firstname by removing academic titles
  data <- data %>%
    mutate(firstname = str_remove_all(firstname, " Bc.| MUDr.| JUDr.| PhDr.|Ing.arch.|Ing. arch.|Ing.Arch.|Ing. Arch.|, Ing.| Ing.|.Ing.| Mgr.|Ing.arch.|Ing.PhD.| PH.D.| PharmDr.| PhDr. Ph.D.| Ph.D.| Dr.| Mgr.et Mgr.| Mgr-| doc. CSc| dipl.um.| PHDr.| RNDr.| doc.DDr.PdD.| Doc. JUDr. Ph.| Ing| -předseda|,, Ph.D|, Ph.D.|,,Mgr.,Ph.D|,, MBA|, Dis.|, Bc MBA|, DiS|, MBA|MBA|,, IWE|, Dis.|, MVDr.|, Di|, RNDr.Ph.D.|, Prof.MUDr.|, ThMgr.| - krajský tajem|, et,|, prof. PhDr.|, RNDr.Ph.D.|, doc. JUDr.|, PhDr., BcA.|PhD| prof| RNDr| PaedDr| doc| Doc| BcA|,Ph.D.|  Mgr|et")) %>%
    mutate(firstname = str_squish(firstname))  # Remove extra spaces and dots
  
  # Handle common typos in firstnames
  typos <- list(
    "Aleš" = "Ales", "Anežka" = "Anezka", "Antonín" = "Antonin", "Alena" = "ALENA", "Boleslav" = "boleslav",
    "Božena" = "Bozena", "Dagmar" = "DAGMAR", "David" = c("DAVID", "david"), "Daniel" = "Daniël",
    "Eliška" = c("Eliska", "eliska"), "František" = c("františek", "Frantisek", "FRANTISEK", "FRANTIŠEK", "frantisek"),
    "Františka" = "Frantiska", "Ivo" = c("Mgr Ivo", "IVO"), "Ignác" = "ignác", "Ivan" = "IVAN", "Ivana" = "ivana",
    "Iva" = "iva", "Igor" = "IGOR", "Janka" = "janka", "Jana" = "jana", "Josef" = c("josef", "JOsef"),
    "Jiří" = c("jiří", "Jiri", "Jiři", "Jirí", "jiri", "JIří", "JIŘÍ", "Jaří", "jiří", "Jjiří"),
    "Jan" = c(" Jan", "jan", "Honza", "JAN"), "Jeroným" = "Jeronym", "Jaroslava" = c("Jarka", "jaroslava"),
    "Jakub" = c("jakub", "Kuba", "kuba", "Jaku"), "Jindřich" = c("Jindrich", "jindřich", "jindrich"),
    "Jaroslav" = c("jaroslav", "JAROSLAV"), "Kristina" = "kristina", "Klára" = c("Klara", "klara"),
    "Kateřina" = c("Katerina", "kateřina", "kateria"), "Karel" = "KAREL", "Lukáš" = c("Lukas", "Lukás", "Lukaš", "lukas", "lukáš"),
    "Leoš" = "Leos", "Lucie" = "lucie", "Libor" = "Bc Libor", "Lubuše" = "LIBUŠE", "Miroslav" = c("MIROSLAV", "miroslav"),
    "Marin" = "marin", "Martin" = c("martin", "Martín"), "Markéta" = c("Marketa", "markéta"),
    "Magdaléna" = c("Magdalena", "Magda"), "Matěj" = c("Matej", "MATEJ", "matej"), "Michal" = "michal",
    "Miluše" = "Miluse", "Marek" = "marek", "Milan" = "MILAN", "Naděžda" = "Naděža", "Ota" = " Ota",
    "Ondřej" = c("Ondrej", "Onřej", "Ondra"), "Olga" = c("olga", "Olg"), "Petr" = c("petr", "Pertr", "PETR", "petr"),
    "Petra" = "petra", "Přemysl" = "Premysl", "Pavlína" = "Pavlina", "Přemek" = "Premek", "Pavol" = "PAVOL",
    "Richard" = "RichaRD", "René" = "Rene", "Radka" = "RRadka", "Rudolf" = "rudolf", "Roman" = "ROMAN",
    "Simon" = "simon", "Šimon" = "šimon", "Štěpánka" = c("Štef.", "Stěpánka", "Stepánka", "Štepanka", "Štepánka", "stepanka"),
    "Štěpán" = c("Stepan", "Stěpán", "Stepán", "Štepan", "Štepán", "Štěpan"), "Šárka" = c("Sarka", "Šarka", "Sárka", "šarka", "šárka"),
    "Štefan" = "Stefan", "Tomáš" = c("IngTomáš", "Tomas", "Tomás", "TOMÁŠ", "TOMAS", "tomas", "tomáš"),
    "Tomášek" = "Tomas", "Terezie" = c("Tereza", "tereza"), "Vendula" = "vendula", "Veronika" = c("Veronika", "veronika"),
    "Václav" = c("Václave", "Vaclav", "Václav", "vaclav", "VÁCLAV"), "Vlastimil" = "VLASTIMIL", "Zdeněk" = c("Zdenek", "zdeněk"),
    "Zdenka" = "zdenka", "Žaneta" = c("Žaneta", "zaneta"), "Jaroslav" = c("Jaro.", "JAROSLAV"), "Zuzana" = c("zuzana", "Zuzana"),
    "Zora" = "zora", "Vladimír" = c("Vladimir", "vladimir", "VLADIMIR"), "Věra" = c("Vera", "Věra", "Věda"),
    "Veronika" = c("veronika", "Veronika", "VERONIKA", "veronika")
  )
  
  # Apply the common typos corrections
  for (correct_name in names(typos)) {
    typo_patterns <- typos[[correct_name]]
    #if (is.character(typo_patterns)) {
    #  typo_patterns <- list(typo_patterns)
    #}
    for (typo_pattern in typo_patterns) {
      data <- data %>%
        mutate(firstname = str_replace_all(firstname, typo_pattern, correct_name))
    }
  }

# Perform the replacements
  library(dplyr)
  library(lubridate)
  
  data <- data %>%
    mutate(
      firstname = ifelse(surname == "Huneš" & birthdate == ymd("1968-11-09"), "Robert", firstname),
      firstname = ifelse(firstname == "Pavel,MVDr., Ph.D, M", "Pavel", firstname),
      firstname = ifelse(firstname == "Vladimít", "Vladimír", firstname),
      surname = ifelse(surname == "Aulická -Jírovcová", "Aulická Jírovcová", surname),
      surname = ifelse(surname == "Hemzáková", "Hemzáčková", surname),
      firstname = ifelse(firstname == "Vítěslav" & surname == "Lapčík" & birthdate == ymd("1965-05-21"), "Vítězslav", firstname),
      surname = ifelse(surname == "Orszulík" & birthdate == ymd("1978-02-27"), "Orszulik", surname),
      surname = ifelse(surname == "ADAMÍK" & birthdate == ymd("1962-03-16"), "Adamík", surname),
      surname = ifelse(surname == "Bohutínský - soudní exekutor" & birthdate == ymd("1966-10-23"), "Bohutínský", surname),
      surname = ifelse(surname == "HŘEBEC", "Hřebec", surname),
      surname = ifelse(surname == "KALABUS", "Kalabus", surname),
      surname = ifelse(surname == "KOFROŇ", "Kofroň", surname),
      surname = ifelse(surname == "KOSUBOVÁ", "Kosubová", surname),
      surname = ifelse(surname == "POLÁŠEK", "Polášek", surname),
      surname = ifelse(surname == "Palyza st.", "Palyza", surname),
      surname = ifelse(surname == "Stehno - ES TRANS", "Stehno", surname),
      surname = ifelse(surname == "VAVŘINEC", "Vavřinec", surname),
      surname = ifelse(surname == "WANECKI-MANAP", "Wanecki", surname),
      surname = ifelse(surname == "Ťulpík - WTC", "Ťulpík", surname),
      firstname = ifelse(firstname == "Jan" & birthdate == ymd("1980-06-17"), "Ján", firstname),
      surname = ifelse(surname == "Baller" & birthdate == ymd("1997-05-15"), "Ballek", surname),
      firstname = ifelse(surname == "Ballek" & birthdate == ymd("1997-05-15"), "Jakub Vojtěch", firstname),
      surname = ifelse(surname == "Friedlova" & birthdate == ymd("1987-05-05"), "Friedlová", surname),
      firstname = ifelse(surname == "Friedlová" & birthdate == ymd("1987-05-05"), "Eliška", firstname),
      surname = ifelse(surname == "Homindova" & birthdate == ymd("1974-07-20"), "Homindová", surname),
      surname = ifelse(firstname == "Beran" & birthdate == ymd("1986-05-26"), "Beran", surname),
      surname = ifelse(firstname == "Nádvorník" & birthdate == ymd("1986-01-18"), "Nádvorník", surname),
      surname = ifelse(firstname == "Rýdl" & birthdate == ymd("1979-10-08"), "Rýdl", surname),
      surname = ifelse(firstname == "Střítecký" & birthdate == ymd("1986-07-03"), "Střítecký", surname),
      surname = ifelse(firstname == "Žůrek" & birthdate == ymd("1984-10-23"), "Žůrek", surname),
      firstname = ifelse(firstname == "Beran" & birthdate == ymd("1986-05-26"), "Jan", firstname),
      firstname = ifelse(firstname == "Nádvorník" & birthdate == ymd("1986-01-18"), "Jan", firstname),
      firstname = ifelse(firstname == "Rýdl" & birthdate == ymd("1979-10-08"), "Jan", firstname),
      firstname = ifelse(firstname == "Střítecký" & birthdate == ymd("1986-07-03"), "Jan", firstname),
      firstname = ifelse(firstname == "Žůrek" & birthdate == ymd("1984-10-23"), "Jan", firstname),
      firstname = ifelse(surname == "Kirš" & birthdate == ymd("1980-05-18"), "Tomáš", firstname),
      surname = ifelse(surname == "Kohoutova" & birthdate == ymd("1989-10-18"), "Kohoutová", surname),
      firstname = ifelse(firstname == "Magdalena Anna" & birthdate == ymd("1989-10-18"), "Magdalena", firstname),
      surname = ifelse(surname == "Komrskova" & birthdate == ymd("1978-02-08"), "Komrsková", surname),
      surname = ifelse(surname == "Krausova" & birthdate == ymd("1992-10-08"), "Krausová", surname),
      surname = ifelse(surname == "Krtičková,", "Krtičková", surname),
      surname = ifelse(firstname == "Šotková" & birthdate == ymd("1968-04-12"), "Šotková", surname),
      firstname = ifelse(firstname == "Šotková" & birthdate == ymd("1968-04-12"), "Lenka", firstname),
      surname = ifelse(firstname == "Vachova" & birthdate == ymd("1979-06-25"), "Vachová", surname),
      firstname = ifelse(firstname == "Vachova" & birthdate == ymd("1979-06-25"), "Libuše", firstname),
      surname = ifelse(surname == "Lorovsky", "Lorovský", surname),
      surname = ifelse(firstname == "Rek" & birthdate == ymd("1990-03-30"), "Rek", surname),
      firstname = ifelse(firstname == "Rek" & birthdate == ymd("1990-03-30"), "Lubomír", firstname),
      surname = ifelse(firstname == "Beránková" & birthdate == ymd("1992-06-01"), "Beránková", surname),
      firstname = ifelse(firstname == "Beránková" & birthdate == ymd("1992-06-01"), "Lucie", firstname),
      surname = ifelse(firstname == "Sokolová" & birthdate == ymd("2001-06-14"), "Sokolová", surname),
      firstname = ifelse(firstname == "Sokolová" & birthdate == ymd("2001-06-14"), "Lucie", firstname),
      firstname = ifelse(firstname == "Martina Jerie" & birthdate == ymd("1971-09-06"), "Martina", firstname),
      firstname = ifelse(firstname == "Zdenek" & birthdate == ymd("1977-08-22") & surname == "Machek", "Zdeněk", firstname),
      firstname = ifelse(firstname == "Giusepe" & birthdate == ymd("1962-06-10"), "Giuseppe", firstname),
      firstname = ifelse(firstname == "Renáta" & birthdate == ymd("1962-06-25"), "Renata", firstname),
      surname = ifelse(firstname == "Chamrád" & birthdate == ymd("2002-04-06"), "Chamrád", surname),
      firstname = ifelse(firstname == "Chamrád" & birthdate == ymd("2002-04-06"), "Michal", firstname),
      surname = ifelse(firstname == "Langer" & birthdate == ymd("1999-10-01"), "Langer", surname),
      firstname = ifelse(firstname == "Langer" & birthdate == ymd("1999-10-01"), "Michal", firstname),
      surname = ifelse(firstname == "Mazík" & birthdate == ymd("1984-09-04"), "Mazík", surname),
      firstname = ifelse(firstname == "Mazík" & birthdate == ymd("1984-09-04"), "Michal", firstname),
      surname = ifelse(firstname == "Trousil" & birthdate == ymd("1979-03-12"), "Trousil", firstname),
      
      firstname = ifelse(firstname == "Trousil" & birthdate == ymd("1979-03-12"), "Michal", firstname),
      firstname = ifelse((firstname == "Ing Zdeněk" & birthdate == ymd("1966-07-27")) | (firstname == "IngZdeněk" & birthdate == ymd("1966-07-27")), "Zdeněk", firstname),
      surname = ifelse(surname == "Ondrackova" & birthdate == ymd("1993-11-22"), "Ondráčková", surname),
      surname = ifelse(firstname == "Bednář" & birthdate == ymd("1978-11-23"), "Bednář", surname),
      firstname = ifelse(firstname == "Bednář" & birthdate == ymd("1978-11-23"), "Ondřej", firstname),
      surname = ifelse(firstname == "Haváč" & birthdate == ymd("1985-09-03"), "Haváč", surname),
      firstname = ifelse(firstname == "Haváč" & birthdate == ymd("1985-09-03"), "Ondřej", firstname),
      surname = ifelse(firstname == "Kolínský" & birthdate == ymd("1990-03-11"), "Kolínský", surname),
      firstname = ifelse(firstname == "Kolínský" & birthdate == ymd("1990-03-11"), "Ondřej", firstname),
      surname = ifelse(firstname == "stalčík" & birthdate == ymd("1975-10-31"), "Stalčík", surname),
      firstname = ifelse(firstname == "stalčík" & birthdate == ymd("1975-10-31"), "Adam", firstname),
      surname = ifelse(surname == "balogova" & birthdate == ymd("1994-09-02"), "Balogová", surname),
      surname = ifelse(surname == "de Bruyn" & birthdate == ymd("1983-07-11"), "De Bruyn", surname),
      surname = ifelse(firstname == "Jindrich" & birthdate == ymd("1988-01-11"), "Devátý", surname),
      firstname = ifelse(firstname == "Jindrich" & birthdate == ymd("1988-01-11"), "Jindřich", firstname),
      surname = ifelse(surname == "fafi" & birthdate == ymd("1990-07-03"), "Fafi", surname),
      surname = ifelse(surname == "fischer" & birthdate == ymd("1965-10-14"), "Fischer", surname),
      surname = ifelse(surname == "fojtek" & birthdate == ymd("1969-01-07"), "Fojtek", surname),
      surname = ifelse(surname == "frauknecht", "Frauknecht", surname),
      surname = ifelse(surname == "gronych", "Gronych", surname),
      surname = ifelse(surname == "hanzal", "Hanzal", surname),
      surname = ifelse(surname == "holas", "Holas", surname),
      surname = ifelse(surname == "hovorková", "Hovorková", surname),
      
      surname = ifelse(surname == "jedlička", "Jedlička", surname),
      surname = ifelse(surname == "junga", "Junga", surname),
      surname = ifelse(surname == "kabelka", "Kabelka", surname),
      surname = ifelse(surname == "karas", "Karas", surname),
      surname = ifelse(surname == "koubkova", "Koubková", surname),
      surname = ifelse(surname == "karger", "Karger", surname),
      surname = ifelse(surname == "kindl", "Kindl", surname),
      surname = ifelse(surname == "michailidu", "Michailidu", surname),
      surname = ifelse(surname == "kolář", "Kolář", surname),
      surname = ifelse(surname == "kopecká", "Kopecká", surname),
      surname = ifelse(surname == "krištiak", "Krištiak", surname),
      surname = ifelse(surname == "kubovciak", "Kubovciak", surname),
      surname = ifelse(surname == "kure", "Kuře", surname),
      surname = ifelse(surname == "libich", "Libich", surname),
      surname = ifelse(surname == "liskova", "Lišková", surname),
      surname = ifelse(surname == "myslivec", "Myslivec", surname),
      surname = ifelse(surname == "panek", "Pánek", surname),
      surname = ifelse(surname == "novotný", "Novotný", surname),
      surname = ifelse(surname == "selinger" | surname == "selinger/knihkupectví", "Selinger", surname),
      surname = ifelse(surname == "pokorná", "Pokorná", surname),
      surname = ifelse(surname == "přečková", "Přečková", surname),
      surname = ifelse(surname == "rebl", "Rebl", surname),
      surname = ifelse(surname == "sebera", "Sebera", surname),
      surname = ifelse(surname == "svoboda", "Svoboda", surname),
      surname = ifelse(surname == "zecha", "Zecha", surname),
      surname = ifelse(surname == "sedlák", "Sedlák", surname),
      surname = ifelse(surname == "seguin", "Seguin", surname),
      surname = ifelse(surname == "tilinger", "Tilinger", surname),
      surname = ifelse(surname == "vlášek", "Vlášek", surname),
      surname = ifelse(surname == "wihan", "Wihan", surname),
      surname = ifelse(surname == "vobecká", "Vobecká", surname),
      surname = ifelse(firstname == "hrůza", "Hrůza", surname),
      firstname = ifelse(firstname == "hrůza", "Ladislav", firstname),
      surname = ifelse(surname == "sklenka", "Sklenka", surname),
      surname = ifelse(surname == "skala", "Skala", surname),
      firstname = ifelse(firstname == "Marri", "Martin", firstname),
      surname = ifelse(surname == "skovajsa", "Skovajsa", surname),
      surname = ifelse(surname == "vendlova", "Vedlová", surname),
      surname = ifelse(surname == "miguele", "Miguele", surname),
      surname = ifelse(surname == "navrat", "Navrat", surname),
      surname = ifelse(surname == "pety", "Pety", surname),
      surname = ifelse(surname == "foltyn(bolsoncar)", "Foltyn", surname),
      surname = ifelse(surname == "Ř?ha", "Řeha", surname),
      surname = ifelse(surname == "ŠPINGL", "Špingl", surname),
      surname = ifelse(firstname == "Jánská" & birthdate == ymd("1963-06-04"), "Jánská", surname),
      firstname = ifelse(firstname == "Jánská" & birthdate == ymd("1963-06-04"), "Alena", firstname),
      surname = ifelse(firstname == "Šeborová" & birthdate == ymd("1957-01-15"), "Šeborová", surname),
      firstname = ifelse(firstname == "Šeborová" & birthdate == ymd("1957-01-15"), "Alena", firstname),
      surname = ifelse(firstname == "Mačková" & birthdate == ymd("1972-09-19"), "Mačková", surname),
      firstname = ifelse(firstname == "Mačková" & birthdate == ymd("1972-09-19"), "Andrea", firstname),
      surname = ifelse(firstname == "Biersacková" & birthdate == ymd("1946-02-06"), "Biersacková", surname),
      firstname = ifelse(firstname == "Biersacková" & birthdate == ymd("1946-02-06"), "Anna", firstname),
      surname = ifelse(firstname == "Dušek" & birthdate == ymd("1956-02-27"), "Dušek", surname),
      firstname = ifelse(firstname == "Dušek" & birthdate == ymd("1956-02-27"), "Antonín", firstname),
      surname = ifelse(firstname == "Impseil" & birthdate == ymd("1995-03-19"), "Impseil", surname),
      firstname = ifelse(firstname == "Impseil" & birthdate == ymd("1995-03-19"), "Daniel", firstname),
      surname = ifelse(firstname == "Šelešovský" & birthdate == ymd("1971-02-10"), "Šelešovský", surname),
      firstname = ifelse(firstname == "Šelešovský" & birthdate == ymd("1971-02-10"), "Daniel", firstname),
      surname = ifelse(firstname == "Urbánková" & birthdate == ymd("1952-10-10"), "Urbánková", surname),
      firstname = ifelse(firstname == "Urbánková" & birthdate == ymd("1952-10-10"), "Daniela", firstname),
      surname = ifelse(firstname == "Bojková" & birthdate == ymd("1963-08-24"), "Bojková", surname),
      firstname = ifelse(firstname == "Bojková" & birthdate == ymd("1963-08-24"), "Darja", firstname),
      
      surname = ifelse(firstname == "Dvořák" & birthdate == ymd("1991-02-03"), "Dvořák", surname),
      firstname = ifelse(firstname == "Dvořák" & birthdate == ymd("1991-02-03"), "David", firstname),
      surname = ifelse(firstname == "Ševčík" & birthdate == ymd("1967-07-04"), "Ševčík", surname),
      firstname = ifelse(firstname == "Ševčík" & birthdate == ymd("1967-07-04"), "David", firstname),
      surname = ifelse(firstname == "Sklenka" & birthdate == ymd("1986-07-13"), "Sklenka", surname),
      firstname = ifelse(firstname == "Sklenka" & birthdate == ymd("1986-07-13"), "David", firstname),
      surname = ifelse(firstname == "Pokorný" & birthdate == ymd("1959-07-31"), "Pokorný", surname),
      firstname = ifelse(firstname == "Pokorný" & birthdate == ymd("1959-07-31"), "David", firstname),
      surname = ifelse(firstname == "Gerneš" & birthdate == ymd("1991-04-25"), "Gerneš", surname),
      firstname = ifelse(firstname == "Gerneš" & birthdate == ymd("1991-04-25"), "David", firstname),
      firstname = ifelse(firstname == "gogo", "Gogo", firstname),
      surname = ifelse(surname == "Filipiecová Bc.", "Filipiecová", surname),
      surname = ifelse(firstname == "Blažek" & birthdate == ymd("1962-02-18"), "Blažek", surname),
      firstname = ifelse(firstname == "Blažek" & birthdate == ymd("1962-02-18"), "Igor", firstname),
      surname = ifelse(firstname == "Jurásek" & birthdate == ymd("1948-01-16"), "Jurásek", surname),
      firstname = ifelse(firstname == "Jurásek" & birthdate == ymd("1948-01-16"), "Igor", firstname),
      surname = ifelse(surname == "Ing.Valenta", "Valenta", surname),
      surname = ifelse(firstname == "Dukátníková" & birthdate == ymd("1989-02-19"), "Dukátníková", surname),
      firstname = ifelse(firstname == "Dukátníková" & birthdate == ymd("1989-02-19"), "Irena", firstname),
      surname = ifelse(firstname == "Nevludová" & birthdate == ymd("1977-07-29"), "Nevludová", surname),
      firstname = ifelse(firstname == "Nevludová" & birthdate == ymd("1977-07-29"), "Ivana", firstname),
      surname = ifelse(firstname == "Ondrušová" & birthdate == ymd("1964-01-24"), "Ondrušová", surname),
      firstname = ifelse(firstname == "Ondrušová" & birthdate == ymd("1964-01-24"), "Ivana", firstname),
      surname = ifelse(firstname == "Škurková" & birthdate == ymd("1962-05-18"), "Škurková", surname),
      firstname = ifelse(firstname == "Škurková" & birthdate == ymd("1962-05-18"), "Iveta", firstname),
      surname = ifelse(firstname == "Švancarová" & birthdate == ymd("1962-04-07"), "Švancarová", surname),
      firstname = ifelse(firstname == "Švancarová" & birthdate == ymd("1962-04-07"), "Iveta", firstname),
      surname = ifelse(firstname == "Jelínek" & birthdate == ymd("1970-06-19"), "Jelínek", surname),
      firstname = ifelse(firstname == "Jelínek" & birthdate == ymd("1970-06-19"), "Ivo", firstname),
      surname = ifelse(firstname == "Havran" & birthdate == ymd("1986-08-04"), "Havran", surname),
      firstname = ifelse(firstname == "Havran" & birthdate == ymd("1986-08-04"), "Jakub", firstname),
      surname = ifelse(firstname == "Morong" & birthdate == ymd("1995-10-02"), "Morong", surname),
      firstname = ifelse(firstname == "Morong" & birthdate == ymd("1995-10-02"), "Jakub", firstname),
      surname = ifelse(firstname == "Bílý" & birthdate == ymd("1984-08-29"), "Bílý", surname),
      firstname = ifelse(firstname == "Bílý" & birthdate == ymd("1984-08-29"), "Jan", firstname),
      surname = ifelse(firstname == "Frišhons" & birthdate == ymd("1984-12-13"), "Frišhons", surname),
      firstname = ifelse(firstname == "Frišhons" & birthdate == ymd("1984-12-13"), "Jan", firstname),
      surname = ifelse(firstname == "Fučík" & birthdate == ymd("1975-06-21"), "Fučík", surname),
      firstname = ifelse(firstname == "Fučík" & birthdate == ymd("1975-06-21"), "Jan", firstname),
      surname = ifelse(firstname == "Mašek" & birthdate == ymd("1984-10-18"), "Mašek", surname),
      firstname = ifelse(firstname == "Mašek" & birthdate == ymd("1984-10-18"), "Jan", firstname),
      surname = ifelse(firstname == "Hrnčíř" & birthdate == ymd("1977-05-01"), "Hrnčíř", surname),
      firstname = ifelse(firstname == "Hrnčíř" & birthdate == ymd("1977-05-01"), "Jan", firstname),
      surname = ifelse(firstname == "Hubený" & birthdate == ymd("1972-03-22"), "Hubený", surname),
      firstname = ifelse(firstname == "Hubený" & birthdate == ymd("1972-03-22"), "Jan", firstname),
      surname = ifelse(firstname == "Ouzký" & birthdate == ymd("1984-06-08"), "Ouzký", surname),
      firstname = ifelse(firstname == "Ouzký" & birthdate == ymd("1984-06-08"), "Jan", firstname),
      surname = ifelse(firstname == "Stöhr" & birthdate == ymd("1989-09-03"), "Stöhr", surname),
      firstname = ifelse(firstname == "Stöhr" & birthdate == ymd("1989-09-03"), "Jan", firstname),
      surname = ifelse(firstname == "Čestický" & birthdate == ymd("1967-05-13"), "Čestický", surname),
      firstname = ifelse(firstname == "Čestický" & birthdate == ymd("1967-05-13"), "Jan", firstname),
      surname = ifelse(firstname == "Štraub" & birthdate == ymd("1971-05-20"), "Štraub", surname),
      firstname = ifelse(firstname == "Štraub" & birthdate == ymd("1971-05-20"), "Jan", firstname),
      
      surname = ifelse(firstname == "Žižka" & birthdate == ymd("1954-09-25"), "Žižka", surname),
      firstname = ifelse(firstname == "Žižka" & birthdate == ymd("1954-09-25"), "Jan", firstname),
      surname = ifelse(firstname == "Žlebek" & birthdate == ymd("1978-07-31"), "Žlebek", surname),
      firstname = ifelse(firstname == "Žlebek" & birthdate == ymd("1978-07-31"), "Jan", firstname),
      surname = ifelse(firstname == "Plevková" & birthdate == ymd("1988-07-25"), "Plevková", surname),
      firstname = ifelse(firstname == "Plevková" & birthdate == ymd("1988-07-25"), "Jana", firstname),
      surname = ifelse(firstname == "Štablová" & birthdate == ymd("1969-10-25"), "Štablová", surname),
      firstname = ifelse(firstname == "Štablová" & birthdate == ymd("1969-10-25"), "Jana", firstname),
      surname = ifelse(firstname == "Levová" & birthdate == ymd("1977-06-17"), "Levová", surname),
      firstname = ifelse(firstname == "Levová" & birthdate == ymd("1977-06-17"), "Jana", firstname),
      surname = ifelse(firstname == "Valigurová" & birthdate == ymd("1969-12-19"), "Valigurová", surname),
      firstname = ifelse(firstname == "Valigurová" & birthdate == ymd("1969-12-19"), "Jana", firstname),
      surname = ifelse(firstname == "Vávrová" & birthdate == ymd("1961-07-08"), "Vávrová", surname),
      firstname = ifelse(firstname == "Vávrová" & birthdate == ymd("1961-07-08"), "Jana", firstname),
      surname = ifelse(firstname == "Dragounová" & birthdate == ymd("1943-11-07"), "Dragounová", surname),
      firstname = ifelse(firstname == "Dragounová" & birthdate == ymd("1943-11-07"), "Jana", firstname),
      surname = ifelse(firstname == "Plevková" & birthdate == ymd("1959-02-04"), "Plevková", surname),
      firstname = ifelse(firstname == "Plevková" & birthdate == ymd("1959-02-04"), "Jarmila", firstname),
      surname = ifelse(firstname == "Hendrychová" & birthdate == ymd("1960-10-27"), "Hendrychová", surname),
      firstname = ifelse(firstname == "Hendrychová" & birthdate == ymd("1960-10-27"), "Jarmila", firstname),
      surname = ifelse(firstname == "Broulík" & birthdate == ymd("1970-04-13"), "Broulík", surname),
      firstname = ifelse(firstname == "Broulík" & birthdate == ymd("1970-04-13"), "Jaromír", firstname),
      surname = ifelse(firstname == "Slíva" & birthdate == ymd("1977-01-07"), "Slíva", surname),
      firstname = ifelse(firstname == "Slíva" & birthdate == ymd("1977-01-07"), "Jaromír", firstname),
      surname = ifelse(firstname == "Wesley" & birthdate == ymd("1954-04-14"), "Wesley", surname),
      firstname = ifelse(firstname == "Wesley" & birthdate == ymd("1954-04-14"), "Eva", firstname),
      surname = ifelse(firstname == "Šťovíčková" & birthdate == ymd("1948-05-25"), "Šťovíčková", surname),
      firstname = ifelse(firstname == "Šťovíčková" & birthdate == ymd("1948-05-25"), "Eva", firstname),
      surname = ifelse(firstname == "Klokočka" & birthdate == ymd("1980-03-22"), "Klokočka", surname),
      firstname = ifelse(firstname == "Klokočka" & birthdate == ymd("1980-03-22"), "Evžen", firstname),
      surname = ifelse(firstname == "Gogo" & birthdate == ymd("1990-07-03"), "Gogo", surname),
      firstname = ifelse(firstname == "Gogo" & birthdate == ymd("1990-07-03"), "Fafi", firstname),
      surname = ifelse(firstname == "Švancarová" & birthdate == ymd("1967-04-07"), "Švancarová", surname),
      firstname = ifelse(firstname == "Švancarová" & birthdate == ymd("1967-04-07"), "Iveta", firstname),
      surname = ifelse(firstname == "Dvořák" & birthdate == ymd("1957-11-04"), "Dvořák", surname),
      firstname = ifelse(firstname == "Dvořák" & birthdate == ymd("1957-11-04"), "Jaroslav", firstname),
      surname = ifelse(firstname == "Holík" & birthdate == ymd("1953-06-29"), "Holík", surname),
      firstname = ifelse(firstname == "Holík" & birthdate == ymd("1953-06-29"), "Jaroslav", firstname),
      surname = ifelse(firstname == "Jána" & birthdate == ymd("1971-03-07"), "Jána", surname),
      firstname = ifelse(firstname == "Jána" & birthdate == ymd("1971-03-07"), "Jaroslav", firstname),
      surname = ifelse(firstname == "Konečný" & birthdate == ymd("1956-07-03"), "Konečný", surname),
      firstname = ifelse(firstname == "Konečný" & birthdate == ymd("1956-07-03"), "Jaroslav", firstname),
      surname = ifelse(firstname == "Nečas" & birthdate == ymd("1964-03-23"), "Nečas", surname),
      firstname = ifelse(firstname == "Nečas" & birthdate == ymd("1964-03-23"), "Jaroslav", firstname),
      surname = ifelse(firstname == "Tyrala" & birthdate == ymd("1981-10-18"), "Tyrala", surname),
      firstname = ifelse(firstname == "Tyrala" & birthdate == ymd("1981-10-18"), "Jaroslav", firstname),
      surname = ifelse(firstname == "Krejcarová" & birthdate == ymd("1991-06-29"), "Krejcarová", surname),
      firstname = ifelse(firstname == "Krejcarová" & birthdate == ymd("1991-06-29"), "Jitka", firstname),
      surname = ifelse(firstname == "Dobešová" & birthdate == ymd("1957-05-28"), "Dobešová", surname),
      firstname = ifelse(firstname == "Dobešová" & birthdate == ymd("1957-05-28"), "Jiřina", firstname),
      surname = ifelse(firstname == "Horáková" & birthdate == ymd("1949-08-16"), "Horáková", surname),
      firstname = ifelse(firstname == "Horáková" & birthdate == ymd("1949-08-16"), "Jiřina", firstname),
      surname = ifelse(firstname == "Dvořák" & birthdate == ymd("1977-07-15"), "Dvořák", surname),
      firstname = ifelse(firstname == "Dvořák" & birthdate == ymd("1977-07-15"), "Jiří", firstname),
      surname = ifelse(firstname == "Kysling" & birthdate == ymd("1979-07-14"), "Kysling", surname),
      firstname = ifelse(firstname == "Kysling" & birthdate == ymd("1979-07-14"), "Jiří", firstname),
      surname = ifelse(firstname == "Strnad" & (birthdate == ymd("1959-09-26") | birthdate == ymd("1959-06-26")), "Strnad", surname),
      firstname = ifelse(firstname == "Strnad" & (birthdate == ymd("1959-09-26") | birthdate == ymd("1959-06-26")), "Jiří", firstname),
      surname = ifelse(firstname == "Čejka" & birthdate == ymd("1983-08-30"), "Čejka", surname),
      firstname = ifelse(firstname == "Čejka" & birthdate == ymd("1983-08-30"), "Jiří", firstname),
      surname = ifelse(firstname == "Soler" & birthdate == ymd("1947-04-20"), "Soler", surname),
      firstname = ifelse(firstname == "Soler" & birthdate == ymd("1947-04-20"), "Jiří", firstname),
      surname = ifelse(firstname == "Nitsche" & birthdate == ymd("1952-04-13"), "Nitsche", surname),
      firstname = ifelse(firstname == "Nitsche" & birthdate == ymd("1952-04-13"), "Jiří", firstname),
      surname = ifelse(firstname == "Kohoutek" & birthdate == ymd("1964-11-26"), "Kohoutek", surname),
      firstname = ifelse(firstname == "Kohoutek" & birthdate == ymd("1964-11-26"), "Jiří", firstname),
      surname = ifelse(firstname == "Kocman" & birthdate == ymd("1955-06-01"), "Kocman", surname),
      firstname = ifelse(firstname == "Kocman" & birthdate == ymd("1955-06-01"), "Jiří", firstname),
      surname = ifelse(firstname == "Kobza" & birthdate == ymd("1955-12-27"), "Kobza", surname),
      firstname = ifelse(firstname == "Kobza" & birthdate == ymd("1955-12-27"), "Jiří", firstname),
      surname = ifelse(firstname == "Antuš" & birthdate == ymd("1973-09-16"), "Antuš", surname),
      firstname = ifelse(firstname == "Antuš" & birthdate == ymd("1973-09-16"), "Jiří", firstname),
      surname = ifelse(firstname == "Pinkava" & birthdate == ymd("1963-10-01"), "Pinkava", surname),
      firstname = ifelse(firstname == "Pinkava" & birthdate == ymd("1963-10-01"), "Jiří", firstname),
      birthdate = ifelse(firstname == "Jiří" & surname == "Strnad" & birthdate == ymd("1959-06-26"), ymd("1959-09-26"), birthdate),
      surname = ifelse(firstname == "Doležal" & birthdate == ymd("1949-03-18"), "Doležal", surname),
      firstname = ifelse(firstname == "Doležal" & birthdate == ymd("1949-03-18"), "John", firstname),
      surname = ifelse(firstname == "Doležal" & birthdate == ymd("1968-05-18"), "Doležal", surname),
      firstname = ifelse(firstname == "Doležal" & birthdate == ymd("1968-05-18"), "Josef", firstname),
      surname = ifelse(firstname == "Kodýtek" & birthdate == ymd("1998-02-04"), "Kodýtek", surname),
      firstname = ifelse(firstname == "Kodýtek" & birthdate == ymd("1998-02-04"), "Josef", firstname),
      surname = ifelse(firstname == "Kopřiva" & birthdate == ymd("1978-10-10"), "Kopřiva", surname),
      firstname = ifelse(firstname == "Kopřiva" & birthdate == ymd("1978-10-10"), "Josef", firstname),
      surname = ifelse(firstname == "Pleva" & birthdate == ymd("1961-06-22"), "Pleva", surname),
      firstname = ifelse(firstname == "Pleva" & birthdate == ymd("1961-06-22"), "Josef", firstname),
      surname = ifelse(firstname == "Sukup" & birthdate == ymd("1959-12-04"), "Sukup", surname),
      firstname = ifelse(firstname == "Sukup" & birthdate == ymd("1959-12-04"), "Josef", firstname),
      surname = ifelse(firstname == "Zakopčan" & birthdate == ymd("1961-05-21"), "Zakopčan", surname),
      firstname = ifelse(firstname == "Zakopčan" & birthdate == ymd("1961-05-21"), "Josef", firstname),
      surname = ifelse(firstname == "Ondřej" & birthdate == ymd("1958-01-28"), "Ondřej", surname),
      firstname = ifelse(firstname == "Ondřej" & birthdate == ymd("1958-01-28"), "Josef", firstname),
      surname = ifelse(surname == "Kadlecova" & birthdate == ymd("1990-07-30"), "Kadlecová", surname),
      firstname = ifelse(firstname == "Stepanka" & birthdate == ymd("1990-07-30"), "Štěpánka", firstname),
      surname = ifelse(firstname == "Běrský" & birthdate == ymd("1958-07-16"), "Běrský", surname),
      firstname = ifelse(firstname == "Běrský" & birthdate == ymd("1958-07-16"), "Kamil", firstname),
      surname = ifelse(firstname == "Kokolusová" & birthdate == ymd("1967-05-29"), "Kokolusová", surname),
      firstname = ifelse(firstname == "Kokolusová" & birthdate == ymd("1967-05-29"), "Kamila", firstname),
      surname = ifelse(firstname == "Bák" & birthdate == ymd("1978-06-04"), "Bák", surname),
      firstname = ifelse(firstname == "Bák" & birthdate == ymd("1978-06-04"), "Karel", firstname),
      surname = ifelse(firstname == "Fiala" & birthdate == ymd("1987-07-12"), "Fiala", surname),
      firstname = ifelse(firstname == "Fiala" & birthdate == ymd("1987-07-12"), "Karel", firstname),
      surname = ifelse(firstname == "Kříž" & birthdate == ymd("1951-03-23"), "Kříž", surname),
      firstname = ifelse(firstname == "Kříž" & birthdate == ymd("1951-03-23"), "Karel", firstname),
      surname = ifelse(firstname == "Oplt" & birthdate == ymd("1945-09-06"), "Oplt", surname),
      firstname = ifelse(firstname == "Oplt" & birthdate == ymd("1945-09-06"), "Karel", firstname),
      surname = ifelse(firstname == "Ošťadnický" & birthdate == ymd("1971-10-06"), "Ošťadnický", surname),
      firstname = ifelse(firstname == "Ošťadnický" & birthdate == ymd("1971-10-06"), "Karel", firstname),
      surname = ifelse(firstname == "Maříková" & birthdate == ymd("1981-03-19"), "Maříková", surname),
      firstname = ifelse(firstname == "Maříková" & birthdate == ymd("1981-03-19"), "Karel", firstname),
      surname = ifelse(surname == "Kolečk?ř" & birthdate == ymd("1994-01-21"), "Kolečkář", surname),
      surname = ifelse(surname == "KrŇanský" & birthdate == ymd("1944-09-04"), "Krňanský", surname),     
      
      surname = ifelse(firstname == "Maříková" & birthdate == ymd("1981-03-19"), "Maříková", surname),
      firstname = ifelse(firstname == "Maříková" & birthdate == ymd("1981-03-19"), "Karel", firstname),
      surname = ifelse(firstname == "Hammer" & birthdate == ymd("1982-03-17"), "Hammer", surname),
      firstname = ifelse(firstname == "Hammer" & birthdate == ymd("1982-03-17"), "Ladislav", firstname),
      surname = ifelse(firstname == "Hora" & birthdate == ymd("1952-06-05"), "Hora", surname),
      firstname = ifelse(firstname == "Hora" & birthdate == ymd("1952-06-05"), "Ladislav", firstname),
      surname = ifelse(firstname == "Ulrych" & birthdate == ymd("1991-11-20"), "Ulrych", surname),
      firstname = ifelse(firstname == "Ulrych" & birthdate == ymd("1991-11-20"), "Ladislav", firstname),
      surname = ifelse(firstname == "Vali" & birthdate == ymd("1964-07-09"), "Vali", surname),
      firstname = ifelse(firstname == "Vali" & birthdate == ymd("1964-07-09"), "Libor", firstname),
      surname = ifelse(firstname == "Volná" & birthdate == ymd("1957-07-03"), "Volná", surname),
      firstname = ifelse(firstname == "Volná" & birthdate == ymd("1957-07-03"), "Libuše", firstname),
      surname = ifelse(firstname == "Volný" & birthdate == ymd("1973-07-03"), "Volný", surname),
      firstname = ifelse(firstname == "Volný" & birthdate == ymd("1973-07-03"), "Lubomír", firstname),
      surname = ifelse(firstname == "Kapr" & birthdate == ymd("1979-08-09"), "Kapr", surname),
      firstname = ifelse(firstname == "Kapr" & birthdate == ymd("1979-08-09"), "Luboš", firstname),
      surname = ifelse(firstname == "Vitásek" & birthdate == ymd("1952-06-24"), "Vitásek", surname),
      firstname = ifelse(firstname == "Vitásek" & birthdate == ymd("1952-06-24"), "Lubomír", firstname),
      surname = ifelse(firstname == "Španěl" & birthdate == ymd("1955-10-01"), "Španěl", surname),
      firstname = ifelse(firstname == "Španěl" & birthdate == ymd("1955-10-01"), "Lubomír", firstname),
      surname = ifelse(firstname == "Burianová" & birthdate == ymd("1987-10-09"), "Burianová", surname),
      firstname = ifelse(firstname == "Burianová" & birthdate == ymd("1987-10-09"), "Lucie", firstname),
      surname = ifelse(firstname == "Šafránková" & birthdate == ymd("1987-05-21"), "Šafránková", surname),
      firstname = ifelse(firstname == "Šafránková" & birthdate == ymd("1987-05-21"), "Lucie", firstname),
      surname = ifelse(firstname == "Štěpánková" & birthdate == ymd("1988-01-06"), "Štěpánková", surname),
      firstname = ifelse(firstname == "Štěpánková" & birthdate == ymd("1988-01-06"), "Lucie", firstname),
      surname = ifelse(firstname == "Mičolová" & birthdate == ymd("1945-02-17"), "Mičolová", surname),
      firstname = ifelse(firstname == "Mičolová" & birthdate == ymd("1945-02-17"), "Ludvika", firstname),
      surname = ifelse(firstname == "Hromada" & birthdate == ymd("1971-04-14"), "Hromada", surname),
      firstname = ifelse(firstname == "Hromada" & birthdate == ymd("1971-04-14"), "Luděk", firstname),
      surname = ifelse(firstname == "Žídek" & birthdate == ymd("1950-10-11"), "Žídek", surname),
      firstname = ifelse(firstname == "Žídek" & birthdate == ymd("1950-10-11"), "Luděk", firstname),
      surname = ifelse(firstname == "Tomešová" & birthdate == ymd("1968-11-04"), "Tomešová", surname),
      firstname = ifelse(firstname == "Tomešová" & birthdate == ymd("1968-11-04"), "Luďka", firstname),
      surname = ifelse(firstname == "Skříčková" & birthdate == ymd("1966-01-31"), "Skříčková", surname),
      firstname = ifelse(firstname == "Skříčková" & birthdate == ymd("1966-01-31"), "Marcela", firstname),
      surname = ifelse(firstname == "Heydušek" & birthdate == ymd("1965-11-02"), "Heydušek", surname),
      firstname = ifelse(firstname == "Heydušek" & birthdate == ymd("1965-11-02"), "Marcel", firstname),
      surname = ifelse(firstname == "Vysocký" & birthdate == ymd("1969-02-23"), "Vysocký", surname),
      firstname = ifelse(firstname == "Vysocký" & birthdate == ymd("1969-02-23"), "Marek", firstname),
      surname = ifelse(firstname == "Žalman" & birthdate == ymd("1974-12-09"), "Žalman", surname),
      firstname = ifelse(firstname == "Žalman" & birthdate == ymd("1974-12-09"), "Marek", firstname),
      birthdate = ifelse(birthdate == ymd("1962-12-25") & firstname == "Bojko", ymd("1962-01-25"), birthdate),
      surname = ifelse(firstname == "Bojko" & birthdate == ymd("1962-01-25"), "Bojko", surname),
      firstname = ifelse(firstname == "Bojko" & birthdate == ymd("1962-01-25"), "Marian", firstname),
      surname = ifelse(firstname == "Švec" & birthdate == ymd("1992-07-10"), "Švec", surname),
      firstname = ifelse(firstname == "Švec" & birthdate == ymd("1992-07-10"), "Marian", firstname),
      surname = ifelse(firstname == "Malcharová" & birthdate == ymd("1963-11-03"), "Malcharová", surname),
      firstname = ifelse(firstname == "Malcharová" & birthdate == ymd("1963-11-03"), "Marie", firstname),
      surname = ifelse(firstname == "Brož" & birthdate == ymd("1981-08-28"), "Brož", surname),
      firstname = ifelse(firstname == "Brož" & birthdate == ymd("1981-08-28"), "Martin", firstname),
      surname = ifelse(firstname == "Bojko" & birthdate == ymd("1982-10-01"), "Bojko", surname),
      firstname = ifelse(firstname == "Bojko" & birthdate == ymd("1982-10-01"), "Martin", firstname),
      surname = ifelse(firstname == "Mihulová" & birthdate == ymd("1968-02-16"), "Mihulová", surname),
      firstname = ifelse(firstname == "Mihulová" & birthdate == ymd("1968-02-16"), "Marta", firstname),
      surname = ifelse(firstname == "Vlčková" & birthdate == ymd("1966-07-01"), "Vlčková", surname),
      firstname = ifelse(firstname == "Vlčková" & birthdate == ymd("1966-07-01"), "Markéta", firstname),
      surname = ifelse(firstname == "Kovaříková" & birthdate == ymd("1947-08-29"), "Kovaříková", surname),
      firstname = ifelse(firstname == "Kovaříková" & birthdate == ymd("1947-08-29"), "Markéta", firstname),
      
      surname = ifelse(firstname == "Pešat" & birthdate == ymd("1985-04-13"), "Pešat", surname),
      firstname = ifelse(firstname == "Pešat" & birthdate == ymd("1985-04-13"), "Martin", firstname),
      surname = ifelse(firstname == "Franzová" & birthdate == ymd("1959-09-10"), "Franzová", surname),
      firstname = ifelse(firstname == "Franzová" & birthdate == ymd("1959-09-10"), "Martina", firstname),
      surname = ifelse(firstname == "Příhoda" & birthdate == ymd("1979-02-01"), "Příhoda", surname),
      firstname = ifelse(firstname == "Příhoda" & birthdate == ymd("1979-02-01"), "Martin", firstname),
      surname = ifelse(firstname == "Plojhar" & birthdate == ymd("1978-06-16"), "Plojhar", surname),
      firstname = ifelse(firstname == "Plojhar" & birthdate == ymd("1978-06-16"), "Martin", firstname),
      surname = ifelse(firstname == "Sokele" & birthdate == ymd("1984-06-10"), "Sokele", surname),
      firstname = ifelse(firstname == "Sokele" & birthdate == ymd("1984-06-10"), "Martin", firstname),
      surname = ifelse(firstname == "Řehák" & birthdate == ymd("1990-03-15"), "Řehák", surname),
      firstname = ifelse(firstname == "Řehák" & birthdate == ymd("1990-03-15"), "Martin", firstname),
      surname = ifelse(firstname == "Malášek" & birthdate == ymd("1970-09-16"), "Malášek", surname),
      firstname = ifelse(firstname == "Malášek" & birthdate == ymd("1970-09-16"), "Martin", firstname),
      surname = ifelse(firstname == "Homolová" & birthdate == ymd("1982-07-01"), "Homolová", surname),
      firstname = ifelse(firstname == "Homolová" & birthdate == ymd("1982-07-01"), "Martina", firstname),
      surname = ifelse(firstname == "Topičová" & birthdate == ymd("1964-11-07"), "Topičová", surname),
      firstname = ifelse(firstname == "Topičová" & birthdate == ymd("1964-11-07"), "Martina", firstname),
      surname = ifelse(firstname == "Kachlík" & birthdate == ymd("1987-01-21"), "Kachlík", surname),
      firstname = ifelse(firstname == "Kachlík" & birthdate == ymd("1987-01-21"), "Matěj", firstname),
      surname = ifelse(firstname == "Nastoupilová" & birthdate == ymd("1989-11-24"), "Nastoupilová", surname),
      firstname = ifelse(firstname == "Nastoupilová" & birthdate == ymd("1989-11-24"), "Michaela", firstname),
      birthdate = ifelse(birthdate == ymd("1982-11-30") & firstname == "Dlouhý", ymd("1980-11-30"), birthdate),
      surname = ifelse(firstname == "Dlouhý" & birthdate == ymd("1980-11-30"), "Dlouhý", surname),
      firstname = ifelse(firstname == "Dlouhý" & birthdate == ymd("1980-11-30"), "Michal", firstname),
      surname = ifelse(firstname == "Kučera" & birthdate == ymd("1975-02-26"), "Kučera", surname),
      firstname = ifelse(firstname == "Kučera" & birthdate == ymd("1975-02-26"), "Michal", firstname),
      surname = ifelse(firstname == "Tecl" & birthdate == ymd("1965-12-08"), "Tecl", surname),
      firstname = ifelse(firstname == "Tecl" & birthdate == ymd("1965-12-08"), "Michal", firstname),
      surname = ifelse(firstname == "Wisiorek" & birthdate == ymd("1977-05-04"), "Wisiorek", surname),
      firstname = ifelse(firstname == "Wisiorek" & birthdate == ymd("1977-05-04"), "Michal", firstname),
      surname = ifelse(firstname == "Imling" & birthdate == ymd("1955-12-05"), "Imling", surname),
      firstname = ifelse(firstname == "Imling" & birthdate == ymd("1955-12-05"), "Mikuláš", firstname),
      surname = ifelse(firstname == "Kuchár" & birthdate == ymd("1968-01-06"), "Kuchár", surname),
      firstname = ifelse(firstname == "Kuchár" & birthdate == ymd("1968-01-06"), "Milan", firstname),
      surname = ifelse(firstname == "Teuchner" & birthdate == ymd("1947-08-08"), "Teuchner", surname),
      firstname = ifelse(firstname == "Teuchner" & birthdate == ymd("1947-08-08"), "Miloš", firstname),
      surname = ifelse(firstname == "Čech" & birthdate == ymd("1960-05-01"), "Čech", surname),
      firstname = ifelse(firstname == "Čech" & birthdate == ymd("1960-05-01"), "Miloslav", firstname),
      surname = ifelse(firstname == "Rozner" & birthdate == ymd("1977-03-29"), "Rozner", surname),
      firstname = ifelse(firstname == "Rozner" & birthdate == ymd("1977-03-29"), "Miloslav", firstname),
      surname = ifelse(firstname == "Vovesný" & birthdate == ymd("1964-12-18"), "Vovesný", surname),
      firstname = ifelse(firstname == "Vovesný" & birthdate == ymd("1964-12-18"), "Milan", firstname),
      surname = ifelse(firstname == "Sek" & birthdate == ymd("1961-10-12"), "Sek", surname),
      firstname = ifelse(firstname == "Sek" & birthdate == ymd("1961-10-12"), "Milan", firstname),
      surname = ifelse(firstname == "Palička" & birthdate == ymd("1980-09-08"), "Palička", surname),
      
      
      firstname = ifelse(firstname == "Palička" & birthdate == ymd("1980-09-08"), "Milan", firstname),
      surname = ifelse(firstname == "Nevlud" & birthdate == ymd("1965-06-16"), "Nevlud", surname),
      firstname = ifelse(firstname == "Nevlud" & birthdate == ymd("1965-06-16"), "Milan", firstname),
      surname = ifelse(firstname == "Křejčířová" & birthdate == ymd("1946-04-06"), "Křejčířová", surname),
      firstname = ifelse(firstname == "Křejčířová" & birthdate == ymd("1946-04-06"), "Miluše", firstname),
      surname = ifelse(firstname == "Lošťák" & birthdate == ymd("1954-11-23"), "Lošťák", surname),
      firstname = ifelse(firstname == "Lošťák" & birthdate == ymd("1954-11-23"), "Miroslav", firstname),
      surname = ifelse(firstname == "Volná" & birthdate == ymd("1946-07-10"), "Volná", surname),
      firstname = ifelse(firstname == "Volná" & birthdate == ymd("1946-07-10"), "Miroslava", firstname),
      surname = ifelse(firstname == "Kleisner" & birthdate == ymd("1984-03-15"), "Kleisner", surname),
      firstname = ifelse(firstname == "Kleisner" & birthdate == ymd("1984-03-15"), "Miroslav", firstname),
      surname = ifelse(firstname == "Šubrt" & birthdate == ymd("1954-10-03"), "Šubrt", surname),
      firstname = ifelse(firstname == "Šubrt" & birthdate == ymd("1954-10-03"), "Miroslav", firstname),
      surname = ifelse(surname == "Nápravnková" & birthdate == ymd("1971-02-22"), "Nápravníková", surname),
      surname = ifelse(firstname == "Smejkal" & birthdate == ymd("1944-12-07"), "Smejkal", surname),
      firstname = ifelse(firstname == "Smejkal" & birthdate == ymd("1944-12-07"), "Oldřich", firstname),
      surname = ifelse(firstname == "Černý" & birthdate == ymd("1965-09-10"), "Černý", surname),
      firstname = ifelse(firstname == "Černý" & birthdate == ymd("1965-09-10"), "Oldřich", firstname),
      surname = ifelse(firstname == "Pech" & birthdate == ymd("1983-05-17"), "Pech", surname),
      firstname = ifelse(firstname == "Pech" & birthdate == ymd("1983-05-17"), "Ondřej", firstname),
      surname = ifelse(firstname == "Farský" & birthdate == ymd("1974-08-30"), "Farský", surname),
      firstname = ifelse(firstname == "Farský" & birthdate == ymd("1974-08-30"), "Patrik", firstname),
      surname = ifelse(firstname == "Klán" & birthdate == ymd("1972-02-05"), "Klán", surname),
      firstname = ifelse(firstname == "Klán" & birthdate == ymd("1972-02-05"), "Patrik", firstname),
      surname = ifelse(firstname == "Bezucha" & birthdate == ymd("1963-09-22"), "Bezucha", surname),
      firstname = ifelse(firstname == "Bezucha" & birthdate == ymd("1963-09-22"), "Pavel", firstname),
      surname = ifelse(firstname == "Domalíp" & birthdate == ymd("1974-02-22"), "Domalíp", surname),
      firstname = ifelse(firstname == "Domalíp" & birthdate == ymd("1974-02-22"), "Pavel", firstname),
      surname = ifelse(firstname == "Jelínek" & birthdate == ymd("1962-10-31"), "Jelínek", surname),
      firstname = ifelse(firstname == "Jelínek" & birthdate == ymd("1962-10-31"), "Pavel", firstname),
      surname = ifelse(firstname == "Kočí" & birthdate == ymd("1959-01-02"), "Kočí", surname),
      firstname = ifelse(firstname == "Kočí" & birthdate == ymd("1959-01-02"), "Pavel", firstname),
      surname = ifelse(firstname == "Pecho" & birthdate == ymd("1974-06-15"), "Pecho", surname),
      firstname = ifelse(firstname == "Pecho" & birthdate == ymd("1974-06-15"), "Pavel", firstname),
      surname = ifelse(firstname == "Popelka" & birthdate == ymd("1968-12-15"), "Popelka", surname),
      firstname = ifelse(firstname == "Popelka" & birthdate == ymd("1968-12-15"), "Pavel", firstname),
      surname = ifelse(firstname == "Suchý" & birthdate == ymd("1991-04-04"), "Suchý", surname),
      firstname = ifelse(firstname == "Suchý" & birthdate == ymd("1991-04-04"), "Pavel", firstname),
      surname = ifelse(firstname == "Vidlička" & birthdate == ymd("1948-02-11"), "Vidlička", surname),
      firstname = ifelse(firstname == "Vidlička" & birthdate == ymd("1948-02-11"), "Pavel", firstname),
      surname = ifelse(firstname == "Šubrt" & birthdate == ymd("1964-04-17"), "Šubrt", surname),
      firstname = ifelse(firstname == "Šubrt" & birthdate == ymd("1964-04-17"), "Pavel", firstname),
      surname = ifelse(surname == "Peksova", "Peksová", surname),
      surname = ifelse(surname == "Balcarova", "Balcarová", surname),
      surname = ifelse(surname == "Bartos", "Bartoš", surname),
      surname = ifelse(surname == "Belšan", "Belšán", surname),
      firstname = ifelse(firstname == "Bc Hana", "Hana", firstname),
      
      surname = ifelse(surname == "Cejkova" & birthdate == ymd("1973-03-29"), "Čejková", surname),
      firstname = ifelse(firstname == "Vaclava" & birthdate == ymd("1973-03-29"), "Václava", firstname),
      surname = ifelse(surname == "Cech" & birthdate == ymd("1986-03-10"), "Čech", surname),
      surname = ifelse(surname == "Cholenska", "Cholenská", surname),
      surname = ifelse(firstname == "Knot" & birthdate == ymd("1994-10-30"), "Knot", surname),
      firstname = ifelse(firstname == "Knot" & birthdate == ymd("1994-10-30"), "Dominik", firstname),
      surname = ifelse(surname == "Dvorak" & birthdate == ymd("1991-01-22"), "Dvořák", surname),
      surname = ifelse(surname == "Dvorakova" & birthdate == ymd("1992-06-01"), "Dvořáková", surname),
      firstname = ifelse(firstname == "Adela" & birthdate == ymd("1992-06-01"), "Adéla", firstname),
      surname = ifelse(surname == "Havlova", "Havlová", surname),
      surname = ifelse(surname == "Holubova", "Holubová", surname),
      firstname = ifelse(firstname == "Jan09", "Jan", firstname),
      firstname = ifelse(firstname == "Zdenek" & birthdate == ymd("1955-11-21"), "Zdeněk", firstname),
      surname = ifelse(surname == "Hromadkova", "Hromadková", surname),
      surname = ifelse(firstname == "Seidl" & birthdate == ymd("1993-02-02"), "Seidl", surname),
      firstname = ifelse(firstname == "Seidl" & birthdate == ymd("1993-02-02"), "Jakub", firstname),
      surname = ifelse(surname == "Jedelsky", "Jedelský", surname),
      surname = ifelse(surname == "Jiraskova", "Jirásková", surname),
      surname = ifelse(firstname == "Řezníčková" & birthdate == ymd("1973-09-24"), "Řezníčková", surname),
      firstname = ifelse(firstname == "Řezníčková" & birthdate == ymd("1973-09-24"), "Jitka", firstname),
      surname = ifelse(firstname == "Bartošová" & birthdate == ymd("1986-10-30"), "Bartošová", surname),
      firstname = ifelse(firstname == "Bartošová" & birthdate == ymd("1986-10-30"), "Jiřina", firstname),
      surname = ifelse(firstname == "Ulrychová" & birthdate == ymd("1981-04-03"), "Ulrychová", surname),
      firstname = ifelse(firstname == "Ulrychová" & birthdate == ymd("1981-04-03"), "Jiřina", firstname),
      surname = ifelse(firstname == "Bartoš" & birthdate == ymd("1969-02-22"), "Bartoš", surname),
      firstname = ifelse(firstname == "Bartoš" & birthdate == ymd("1969-02-22"), "Jiří", firstname),
      surname = ifelse(firstname == "Růžička" & birthdate == ymd("1978-02-02"), "Růžička", surname),
      firstname = ifelse(firstname == "Růžička" & birthdate == ymd("1978-02-02"), "Jiří", firstname),
      surname = ifelse(surname == "Kalendova", "Kalendová", surname),
      surname = ifelse(surname == "Kleptar", "Klepetář", surname),
      surname = ifelse(surname == "Konecny", "Konečný", surname),
      surname = ifelse(surname == "Kopecka" & birthdate == ymd("1979-09-22"), "Kopecká", surname),
      firstname = ifelse(firstname == "Vladimira" & birthdate == ymd("1979-09-22"), "Vladimíra", firstname),
      surname = ifelse(surname == "Kopecky", "Kopecký", surname),
      firstname = ifelse(firstname == "Regína" & birthdate == ymd("1962-05-17"), "Regina", firstname),
      surname = ifelse(surname == "LEPKOVÁ", "Lepková", surname),
      surname = ifelse(firstname == "Nesnera" & birthdate == ymd("1970-10-06"), "Nesnera", surname),
      firstname = ifelse(firstname == "Nesnera" & birthdate == ymd("1970-10-06"), "Ladislav", firstname),
      surname = ifelse((surname == "Laznovský" & birthdate == ymd("1980-03-06")) | (surname == "Lazznovsky" & birthdate == ymd("1980-03-06")), "Lažnovský", surname),
      surname = ifelse(surname == "Marianek", "Mariánek", surname),
      
      surname = ifelse(firstname == "Urbanová" & birthdate == ymd("1982-10-20"), "Urbanová", surname),
      firstname = ifelse(firstname == "Urbanová" & birthdate == ymd("1982-10-20"), "Marta", firstname),
      surname = ifelse(firstname == "Havlíček" & birthdate == ymd("2000-04-24"), "Havlíček", surname),
      firstname = ifelse(firstname == "Havlíček" & birthdate == ymd("2000-04-24"), "Martin", firstname),
      surname = ifelse(firstname == "Korčák" & birthdate == ymd("1974-10-30"), "Korčák", surname),
      firstname = ifelse(firstname == "Korčák" & birthdate == ymd("1974-10-30"), "Martin", firstname),
      surname = ifelse(surname == "Mayer Soukromé", "Mayer", surname),
      surname = ifelse(surname == "Moravova", "Moravová", surname),
      surname = ifelse(surname == "Necas", "Nečas", surname),
      surname = ifelse(firstname == "Mrázová" & birthdate == ymd("1984-04-02"), "Mrázová", surname),
      firstname = ifelse(firstname == "Mrázová" & birthdate == ymd("1984-04-02"), "Nikola", firstname),
      surname = ifelse(surname == "Novak", "Novák", surname),
      surname = ifelse(surname == "Novotny", "Novotný", surname),
      firstname = ifelse(firstname == "Olga Nováková", "Olga", firstname),
      surname = ifelse(surname == "Oborny", "Oborný", surname),
      surname = ifelse(surname == "Oborsky", "Oborský", surname),
      firstname = ifelse(firstname == "tom", "Tom", firstname),
      surname = ifelse(surname == "Pospisil", "Pospíšil", surname),
      firstname = ifelse(firstname == "Antonin", "Antonín", firstname),
      
      surname = ifelse(surname == "PÍREK", "Pírek", surname),
      surname = ifelse(firstname == "Kšicová" & birthdate == ymd("1987-01-07"), "Kšicová", surname),
      firstname = ifelse(firstname == "Kšicová" & birthdate == ymd("1987-01-07"), "Radka", firstname),
      firstname = ifelse(firstname == "Jaromir" & surname == "Rain" & birthdate == ymd("1958-01-08"), "Jaromír", firstname),
      firstname = ifelse(firstname == "Rozsypal Vojtěch" & birthdate == ymd("2004-05-24"), "Vojtěch", firstname),
      surname = ifelse(surname == "Sabó", "Sabo", surname),
      surname = ifelse(surname == "Sellers-Zajic", "Sellers-Zajíc", surname),
      firstname = ifelse(firstname == "Vojtech" & surname == "Sidorin", "Vojtěch", firstname),
      surname = ifelse(surname == "Sivacek" & birthdate == ymd("1984-09-05"), "Siváček", surname),
      surname = ifelse(surname == "Spacek" & firstname == "Lubomir", "Špaček", surname),
      firstname = ifelse(surname == "Špaček" & firstname == "Lubomir", "Lubomír", firstname),
      surname = ifelse(surname == "Sedlak", "Sedlák", surname),
      surname = ifelse(surname == "Stanek", "Staněk", surname),
      surname = ifelse(surname == "Sykora", "Sýkora", surname),
      surname = ifelse(surname == "Tomasek", "Tomášek", surname),
      surname = ifelse(surname == "Tomkova", "Tomková", surname),
      surname = ifelse(surname == "Tomsikova", "Tomšíková", surname),
      surname = ifelse(surname == "Totuaurova" | surname == "Totzauerova", "Totzauerová", surname),
      surname = ifelse(surname == "Triskova Koskova", "Kosková Třísková", surname),
      surname = ifelse(surname == "Tresnakova", "Třešňáková", surname),
      surname = ifelse(surname == "TurJanicová", "Turjanicová", surname),
      surname = ifelse(surname == "Toth", "Tóth", surname),
      surname = ifelse(surname == "Urtešlégr", "Uretšlégr", surname),
      surname = ifelse(surname == "Valencikova", "Valenčíková", surname),
      surname = ifelse(surname == "Volemanova", "Volemanová", surname),
      surname = ifelse(surname == "Wageknecht" & polparty == 4, "Wagenknecht", surname),
      firstname = ifelse(firstname == "David František", "David", firstname),
      surname = ifelse(surname == "Wirthova", "Wirthová", surname),
      surname = ifelse(surname == "Zahumenska", "Zahumenská", surname),
      surname = ifelse(surname == "Zamorova", "Zamorová", surname),
      surname = ifelse(surname == "Zemanek", "Zemánek", surname),
      surname = ifelse(surname == "špryňarová gottletová", "Špryňarová Gottletová", surname),
      surname = ifelse(firstname == "Hynar" & birthdate == ymd("1991-05-25"), "Hynar", surname),
      firstname = ifelse(firstname == "Hynar" & birthdate == ymd("1991-05-25"), "Adam", firstname),
      surname = ifelse(firstname == "Krajča" & birthdate == ymd("1977-07-15"), "Krajča", surname),
      firstname = ifelse((firstname == "Krajča" & birthdate == ymd("1977-07-15")) | (firstname == "Adrián" & birthdate == ymd("1977-07-15")), "Adrian", firstname),
      surname = ifelse(firstname == "Pavelková" & birthdate == ymd("1957-12-02"), "Pavelková", surname),
      firstname = ifelse(firstname == "Pavelková" & birthdate == ymd("1957-12-02"), "Anna", firstname),
      surname = ifelse(firstname == "Šilar" & birthdate == ymd("1961-02-22"), "Šilar", surname),
      firstname = ifelse(firstname == "Šilar" & birthdate == ymd("1961-02-22"), "Bohuslav", firstname),
      surname = ifelse(firstname == "Dudzik" & birthdate == ymd("1952-02-12"), "Dudzik", surname),
      firstname = ifelse(firstname == "Dudzik" & birthdate == ymd("1952-02-12"), "Bronislav", firstname),
      surname = ifelse(firstname == "Nevludová" & birthdate == ymd("1963-12-16"), "Nevludová", surname),
      firstname = ifelse(firstname == "Nevludová" & birthdate == ymd("1963-12-16"), "Bronislava", firstname),
      surname = ifelse(firstname == "Marková" & birthdate == ymd("1957-01-30"), "Marková", surname),
      
      firstname = ifelse(firstname == "Marková" & birthdate == ymd("1957-01-30"), "Dagmar", firstname),
      surname = ifelse(firstname == "Vlk" & birthdate == ymd("1974-05-16"), "Vlk", surname),
      firstname = ifelse(firstname == "Vlk" & birthdate == ymd("1974-05-16"), "Dalibor", firstname),
      surname = ifelse(firstname == "Kabrna" & birthdate == ymd("1950-08-31"), "Kabrna", surname),
      firstname = ifelse(firstname == "Kabrna" & birthdate == ymd("1950-08-31"), "František", firstname),
      surname = ifelse(firstname == "Kauer" & birthdate == ymd("1959-12-27"), "Kauer", surname),
      firstname = ifelse(firstname == "Kauer" & birthdate == ymd("1959-12-27"), "František", firstname),
      surname = ifelse(firstname == "Klásek" & birthdate == ymd("1955-12-16"), "Klásek", surname),
      firstname = ifelse(firstname == "Klásek" & birthdate == ymd("1955-12-16"), "František", firstname),
      surname = ifelse(firstname == "Konrád" & birthdate == ymd("1951-06-26"), "Konrád", surname),
      firstname = ifelse(firstname == "Konrád" & birthdate == ymd("1951-06-26"), "František", firstname),
      surname = ifelse(firstname == "Kosner" & birthdate == ymd("1959-07-04"), "Kosner", surname),
      firstname = ifelse(firstname == "Kosner" & birthdate == ymd("1959-07-04"), "František", firstname),
      surname = ifelse(firstname == "Kulhánek" & birthdate == ymd("1950-12-10"), "Kulhánek", surname),
      firstname = ifelse(firstname == "Kulhánek" & birthdate == ymd("1950-12-10"), "František", firstname),
      surname = ifelse(firstname == "Roháček" & birthdate == ymd("1947-08-06"), "Roháček", surname),
      firstname = ifelse(firstname == "Roháček" & birthdate == ymd("1947-08-06"), "František", firstname),
      surname = ifelse(firstname == "Wawrzacz" & birthdate == ymd("1957-12-01"), "Wawrzacz", surname),
      firstname = ifelse(firstname == "Wawrzacz" & birthdate == ymd("1957-12-01"), "František", firstname),
      surname = ifelse(firstname == "Čada" & birthdate == ymd("1979-12-15"), "Čada", surname),
      firstname = ifelse(firstname == "Čada" & birthdate == ymd("1979-12-15"), "František", firstname),
      surname = ifelse(firstname == "Vrátná" & birthdate == ymd("1971-03-01"), "Vrátná", surname),
      firstname = ifelse(firstname == "Vrátná" & birthdate == ymd("1971-03-01"), "Gabriela", firstname),
      surname = ifelse(firstname == "Jára" & birthdate == ymd("1974-04-27"), "Jára", surname),
      firstname = ifelse(firstname == "Jára" & birthdate == ymd("1974-04-27"), "Leoš", firstname),
      surname = ifelse(firstname == "Heitel" & birthdate == ymd("1986-11-20"), "Heitel", surname),
      firstname = ifelse(firstname == "Heitel" & birthdate == ymd("1986-11-20"), "Lukáš", firstname),
      surname = ifelse(firstname == "Charousová" & birthdate == ymd("1974-02-23"), "Charousová", surname),
      firstname = ifelse(firstname == "Charousová" & birthdate == ymd("1974-02-23"), "Monika", firstname),
      surname = ifelse(firstname == "Jarošová" & birthdate == ymd("1970-12-30"), "Jarošová", surname),
      firstname = ifelse(firstname == "Jarošová" & birthdate == ymd("1970-12-30"), "Monika", firstname),
      surname = ifelse(surname == "Owcarzy", "Owczarzy", surname),
      surname = ifelse(firstname == "Brázda" & birthdate == ymd("1954-06-07"), "Brázda", surname),
      firstname = ifelse(firstname == "Brázda" & birthdate == ymd("1954-06-07"), "Petr", firstname),
      surname = ifelse(firstname == "Doležel" & birthdate == ymd("1962-10-29"), "Doležel", surname),
      firstname = ifelse(firstname == "Doležel" & birthdate == ymd("1962-10-29"), "Petr", firstname),
      surname = ifelse(firstname == "Dostálek" & birthdate == ymd("1973-12-18"), "Dostálek", surname),
      firstname = ifelse(firstname == "Dostálek" & birthdate == ymd("1973-12-18"), "Petr", firstname),
      surname = ifelse(firstname == "Drbal" & birthdate == ymd("1978-09-12"), "Drbal", surname),
      firstname = ifelse(firstname == "Drbal" & birthdate == ymd("1978-09-12"), "Petr", firstname),
      surname = ifelse(firstname == "Hercik" & birthdate == ymd("1969-10-18"), "Hercik", surname),
      firstname = ifelse(firstname == "Hercik" & birthdate == ymd("1969-10-18"), "Petr", firstname),
      surname = ifelse(firstname == "Kovář" & birthdate == ymd("1983-06-16"), "Kovář", surname),
      firstname = ifelse(firstname == "Kovář" & birthdate == ymd("1983-06-16"), "Petr", firstname),
      surname = ifelse(firstname == "Krejčiřík" & birthdate == ymd("1967-11-04"), "Krejčiřík", surname),
      firstname = ifelse(firstname == "Krejčiřík" & birthdate == ymd("1967-11-04"), "Petr", firstname),
      
      surname = ifelse(firstname == "Laco" & birthdate == ymd("1964-02-06"), "Laco", surname),
      firstname = ifelse(firstname == "Laco" & birthdate == ymd("1964-02-06"), "Petr", firstname),
      surname = ifelse(firstname == "Macek" & birthdate == ymd("1991-08-19"), "Macek", surname),
      firstname = ifelse(firstname == "Macek" & birthdate == ymd("1991-08-19"), "Petr", firstname),
      surname = ifelse(firstname == "Mašíček" & birthdate == ymd("1978-02-10"), "Mašíček", surname),
      firstname = ifelse(firstname == "Mašíček" & birthdate == ymd("1978-02-10"), "Petr", firstname),
      surname = ifelse(firstname == "Mrňavý" & birthdate == ymd("1980-12-08"), "Mrňavý", surname),
      firstname = ifelse(firstname == "Mrňavý" & birthdate == ymd("1980-12-08"), "Petr", firstname),
      surname = ifelse(firstname == "Pech" & birthdate == ymd("1996-11-07"), "Pech", surname),
      firstname = ifelse(firstname == "Pech" & birthdate == ymd("1996-11-07"), "Petr", firstname),
      surname = ifelse(firstname == "Sklenář" & birthdate == ymd("1949-05-20"), "Sklenář", surname),
      firstname = ifelse(firstname == "Sklenář" & birthdate == ymd("1949-05-20"), "Petr", firstname),
      surname = ifelse(firstname == "Pustějovský" & birthdate == ymd("1971-05-09"), "Pustějovský", surname),
      firstname = ifelse(firstname == "Pustějovský" & birthdate == ymd("1971-05-09"), "René", firstname),
      surname = ifelse(firstname == "Broda" & birthdate == ymd("1979-02-08"), "Broda", surname),
      firstname = ifelse(firstname == "Broda" & birthdate == ymd("1979-02-08"), "Richard", firstname),
      surname = ifelse(firstname == "Michenka" & birthdate == ymd("1970-08-23"), "Michenka", surname),
      firstname = ifelse(firstname == "Michenka" & birthdate == ymd("1970-08-23"), "Richard", firstname),
      surname = ifelse(firstname == "Měchura" & birthdate == ymd("1978-06-28"), "Měchura", surname),
      firstname = ifelse(firstname == "Měchura" & birthdate == ymd("1978-06-28"), "Richard", firstname),
      surname = ifelse(firstname == "Staržec" & birthdate == ymd("1969-10-23"), "Staržec", surname),
      firstname = ifelse(firstname == "Staržec" & birthdate == ymd("1969-10-23"), "Richard", firstname),
      surname = ifelse(firstname == "Vymola" & birthdate == ymd("1968-03-23"), "Vymola", surname),
      firstname = ifelse(firstname == "Vymola" & birthdate == ymd("1968-03-23"), "Robert", firstname),
      surname = ifelse(firstname == "Čapkovič" & birthdate == ymd("1973-12-22"), "Čapkovič", surname),
      firstname = ifelse(firstname == "Čapkovič" & birthdate == ymd("1973-12-22"), "Robert", firstname),
      surname = ifelse(firstname == "Široký" & birthdate == ymd("1970-08-30"), "Široký", surname),
      firstname = ifelse(firstname == "Široký" & birthdate == ymd("1970-08-30"), "Robert", firstname),
      surname = ifelse(firstname == "Hába" & birthdate == ymd("1986-03-02"), "Hába", surname),
      firstname = ifelse(firstname == "Hába" & birthdate == ymd("1986-03-02"), "Roman", firstname),
      surname = ifelse(firstname == "Owczarzy" & birthdate == ymd("1968-02-18"), "Owczarzy", surname),
      firstname = ifelse(firstname == "Owczarzy" & birthdate == ymd("1968-02-18"), "Roman", firstname),
      surname = ifelse(firstname == "Razdíková" & birthdate == ymd("1961-08-21"), "Razdíková", surname),
      firstname = ifelse(firstname == "Razdíková" & birthdate == ymd("1961-08-21"), "Růžena", firstname),
      surname = ifelse(firstname == "Toningerová" & birthdate == ymd("1946-07-09"), "Toningerová", surname),
      firstname = ifelse(firstname == "Toningerová" & birthdate == ymd("1946-07-09"), "Růžena", firstname),
      surname = ifelse(surname == "Sedlák BTh.", "Sedlák", surname),
      surname = ifelse(firstname == "Šatná" & birthdate == ymd("1972-07-12"), "Šatná", surname),
      firstname = ifelse(firstname == "Šatná" & birthdate == ymd("1972-07-12"), "Světlana", firstname),
      surname = ifelse(firstname == "Okamura" & birthdate == ymd("1972-07-04"), "Okamura", surname),
      firstname = ifelse(firstname == "Okamura" & birthdate == ymd("1972-07-04"), "Tomio", firstname),
      surname = ifelse(firstname == "Balcar" & birthdate == ymd("1969-06-02"), "Balcar", surname),
      firstname = ifelse(firstname == "Balcar" & birthdate == ymd("1969-06-02"), "Tomáš", firstname),
      surname = ifelse(firstname == "Cikán" & birthdate == ymd("1969-03-23"), "Cikán", surname),
      firstname = ifelse(firstname == "Cikán" & birthdate == ymd("1969-03-23"), "Tomáš", firstname)
    )


# Save the cleaned data to a new .dta file
saveRDS(data, paste0("cleaned_data/donation_data_cleaned_", d, ".rds"))
}


